spring:
  application:
    name: ClickUp
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
  datasource:
    password: ${DB_PASSWORD}
    url: ${DB_URL}
    username: ${DB_USERNAME}
  mail:
    host: smtp.yandex.ru
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
jwt:
  secret: ${JWT_PASSWORD}
  expiration: ${JWT_EXPIRATION}
logging:
  file:
    name: logs/click-up.log
  level:
    root: info
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    display-request-duration: true
    try-it-out-enabled: true