spring:
  application:
    name: ClickUp
  jpa:
    database: PostgreSQL
    show-sql: true
    hibernate:
      ddl-auto: create
    open-in-view: false
  datasource:
    password: 719
    url: jdbc:postgresql://localhost:5432/clickup_db
    username: postgres
    driver-class-name: org.postgresql.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: contentmaker2611@gmail.com
    password: "ozodbek74780399"
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

jwt:
  secret: "pWcRlY1LSo3WJswuiytWClLNOmk9pon1CvtvaiI7-Oc"
  expiration: 86400000      # 1 kun (ms)
  refresh-expiration: 604800000  # 7 kun