spring:
  application:
    name: ClickUp
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    open-in-view: false
  datasource:
    password: 719
    url: jdbc:postgresql://localhost:5432/clickup_db
    username: postgres
  mail:
    host: smtp.yandex.ru
    port: 587
    username: "ozodbek719@yandex.ru"
    password: "wqwzusffesnfumap"
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
jwt:
  secret: "pWcRlY1LSo3WJswuiytWClLNOmk9pon1CvtvaiI7-Oc"
  expiration: 86400000
logging:
  file:
    name: logs/click-up.log
  level:
    root: info